WIP: Create Signer Container
tiiuae/scs-pki-research pull request #5
Opened 2023-05-31 08:21 UTC by alextserepov

- Docker container with tools
  - USB rules for accessing Yubikey
  - openssl config for Yubikey

2023-06-20 09:40 UTC, cazfi commented on yubikey/start.sh
> +#!/bin/bash
I would either move files that get copied inside the container in a subdirectory, or document the situation by providing a .dockerignore -file that lists these files (this file) that are to be used on host side (only).

2023-06-20 10:47 UTC, jenninikko reviewed
I will be a little tedious)
A few comments from my side.

2023-06-20 10:47 UTC, jenninikko commented on README.md
>  # scs-pki-research
An empty line is needed after the heading and a period at the end of the sentence.
Please check other headings, it is a good rule to wrap a heading with lines: two newlines before and one after.

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +# Example signing:
Let's get rid of a colon here.

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +Generate SHA256 hash
Please put a colon here.

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +Sign the hash with Yubikey
Sign the hash with the Yubikey:

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +Verify the signature (Valid case)
1. Verify the signature (valid case):
2. Add an empty line before and after the code line.

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +`alex@alex-unikie:~/repos/scs-pki-research/yubikey$ ./start.sh --verify --h=1e648d85a8ca1c6f55fcc060bbcbd24a4ff2deb5844e198088689ca840f3337a --sg=499OENQ5B08XVLL4nBJdeoWfYl2TbQEatp1SxeDMnqf527ie6OVBr
Needs ` at the end.

2023-06-20 10:47 UTC, jenninikko commented on README.md
> +YubiKey found on USB Bus: 003, Device: 002
The YubiKey is found on a USB, Bus: 003, Device: 002.

2023-06-20 10:47 UTC, jenninikko commented on README.md
>  # scs-pki-research
SPDX license identifier?

2023-06-21 06:52 UTC, tervis-unikie requested changes
Please squash your commits. 
This is difficult to review having so many changes in many commits. 
And we don't want to merge a bunch commits doing things slightly wrong and then bunch of commits fixing the things, when we can have only commits that just do things right. :) 

Just reminding that, it is okay to force push into PR branches when doing changes.

Maybe while you're at it you might want to combine some docker RUN steps as much as possible, by concatenating commands with "&&". This will require less intermediate containers.

2023-07-08 04:00 UTC, cazfi commented on yubikey/start.sh
> +    echo "$0 --sign -h 35b5d3b9746967f4c1984f90d9ccccda6862abd8dc2546a9b8c663c610696617 > signature.b64"
Examples have wrong syntax. Should be "--h=???" (not "-h ???" or "--h ???")

2023-08-16 10:54 UTC, merged